# spring应用信息
spring:
  # cloud设置
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # 关闭负载均衡器的ribbon，解决一些警告

  # security配置
  security:
    user:
      name: admin # 配置可认证登录服务器的账号密码
      password: 123456