# application.yaml存储多个服务共享的配置，比如数据源、redis等一些服务配置信息通常一个项目的多个微服务都是使用同一套
# 测试
project:
  config:
    datasource:
      url: jdbc:mysql://localhost:3306/vblog?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    redis:
      host: localhost
    eureka:
      defaultZone: http://localhost:2000/eureka

# spring配置信息
spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vblog?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: coffee
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # cloud设置
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # 关闭负载均衡器的ribbon，解决一些警告

  # redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    #jedis:
    pool.max-active: 8
    pool.max-idle: 8
    pool.max-wait: -1ms
    pool.min-idle: 0
    timeout: 3000