# spring应用信息
spring:
  # cloud设置
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # 关闭负载均衡器的ribbon，解决一些警告
    # consul配置
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
      #ribbon:
      #  enabled: false