# hystrix-dashboard配置
hystrix:
  dashboard:
    proxy-stream-allow-list: ${server.address} # 允许代理调用获取数据流的主机列表，配置不当可能无法调用/turbine.stream接口获取熔断信息

# turbine配置：监控多个服务的熔断情况
turbine:
  combine-host-port: true
  app-config: micro-service-consumer,micro-service-provider # 要监控多个应用可以使用逗号隔开
  cluster-name-expression: new String("default") # 集群名字
  aggregator:
    cluster-config: default
  instanceUrlSuffix: /actuator/hystrix.stream # 调用被监控服务的数据流接口地址，缺省/actuator/hystrix.stream