# 服务器信息
server:
  address: localhost
  port: 4999
  servlet:
    context-path: /uaa # 设置一个上下文路径，避免携带不必要的cookie信息

# spring应用信息
spring:
  application:
    name: oauth2-provider

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    address: localhost:3306
    url: jdbc:mysql://${spring.datasource.address}/vblog?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: coffee
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # cloud设置
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # 关闭负载均衡器的ribbon，解决一些警告

# eureka设置
eureka:
  instance:
    hostname: ${server.address}
    instance-id: ${spring.application.name}:${server.address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka # 注册中心服务地址

logging:
  level:
    com.fandou.coffee.learning.springcloud.oauth2.provider: DEBUG